Damego/ETIS-mobile

App.js
http/client.js

feat: add http endpoints

---

http/client.js

refactor(http): Добавлены параметры и мини документация

---

App.js
package.json
utils/storage.js

feat: Добавление хранилища данных

---

App.js
components/Form.js
utils/http.js

feat: Реализация автоматической авторизации

---

navigation/ServicesStackNavigator.jsx
screens/services/Menu.jsx
screens/teachers/Teacher.jsx
screens/teachers/TeacherTable.jsx
screens/teachers/index.js
utils/parser.js

https://github.com/users/Damego/projects/1?pane=issue&itemId=27538626 #

feat: teacher table

---

package-lock.json
package.json
screens/auth/Auth.jsx
screens/auth/AuthButton.jsx
screens/auth/AuthForm.jsx
screens/recovery/RequestButton.jsx
screens/recovery/SendEmail.jsx
screens/recovery/SendEmailForm.jsx
utils/http.js

Добавлен флажок сохранения пароля и кнопка восстановления пароля на экран логина
Также добавлена отправка формы при сабмите на последнем текстовом поле (поле пароля для логина и поле почты для восстановления)

feat: password recovery

---

package-lock.json
package.json
screens/auth/Auth.jsx
screens/auth/AuthButton.jsx
screens/auth/AuthForm.jsx
screens/recovery/RequestButton.jsx
screens/recovery/SendEmail.jsx
screens/recovery/SendEmailForm.jsx
utils/http.js

Теперь при отправке запроса на логин/восстановление пароля токен рекапчи будет получен заново, перезапуск приложения больше не требуется
Ребейз от #31

fix: recaptcha token

---

components/Dropdown.jsx
screens/settings/Settings.tsx

При выборе элемента дропдаун ресайзается до размера строки, вместе с ним и выпадающее меню изменяется в размерах

fix: fixate dropdown size

---

src/components/PageNavigator.tsx
src/screens/timeTable/TimeTable.tsx

Часто бывает, что переключился на какую-нибудь неделю, а потом забыл, какая неделя текущая, и приходится искать её

feat: add border to current week in timetable

---

app.json
package-lock.json
package.json
src/App.tsx
src/navigation/StackNavigator.tsx
src/navigation/TabNavigation.tsx
src/redux/reducers/settingsSlice.ts
src/utils/privacyPolicy.ts
src/utils/shortcuts.ts

Добавил возможность запускать окна приложения по долгому тапу по иконке![Screenshot_2023-08-13-01-07-29-05_b783bf344239542886fee7b48fa4b892](https://github.com/Damego/ETIS-mobile/assets/53531892/88d53b1e-0f07-49b0-acfb-645af5cf55fd)

feat: quick shortcut

---

src/cache/fieldCache.ts
src/cache/mappedCache.ts

Добавил мета-информацию к кешируемым данным - время кеширования, в будущем можно будет использовать её в оффлайн режиме для индикации актуальности данных

feat💥(cache): add timestamp data

---

README.md

chore: wakatime badge

---

src/parser/teachers.ts

Метод парсинга дисциплин и их типов изменен на regex, что бы покрывать различные вариации
Протиестировано следующее: https://regex101.com/r/gvUVMt/3

fix: subject parsing

---

src/screens/auth/AuthForm.tsx

Сообщение об ошибке во время логина теперь покрашено

fix: auth message color

---

app.config.js
package-lock.json
package.json
src/App.tsx
src/navigation/StackNavigator.tsx
src/navigation/TabNavigation.tsx
src/utils/sentry.ts
src/utils/shortcuts.ts

Интегрирована система репортинга ошибок sentry.io
Для сохранения конфеденциальности данных запуск интеграции происходит исключительно по шорткату "Отладочный запуск".
Тем не менее даже в отладочном запуске на сторонние сервера конфеденциальная информация (т.е. логины/пароли, кешированные данные) не передаются. 
В список обрабатываемой информации входит следующее: 
* устройство запуска (OS, версия, модель устройства и т.д)
* метаданные приложения (версия, ветка разработки)
* логи сетевой активности (url запросов, время, но не содержание!)
* трейс ошибки (точка возникновения исключения)
Данное изменение поможет получать отчеты об ошибках быстро и полно
Тем не менее потребуются соответсвующие изменения в политику конфеденциальности

feat: sentry error-reporting

---

src/components/Dropdown.tsx
src/components/SessionDropdown.tsx

Добавил кнопку для текущего списка в дропдавн оценок и рейтинга

fix: missed trimester

---

package-lock.json
package.json

Типы от реакт нейтива куда то потерялись

build(deps): add @types/react-native

---

src/data/base.ts
src/parser/timeTable.ts
src/utils/certificate.ts
src/utils/consts.js
src/utils/debug.ts
src/utils/sentry.ts

Алерт бокс при ошибке парсинга

feat(parser): send trace in sentry else show alert on error

---

src/models/timeTable.ts
src/parser/timeTable.ts
src/screens/timeTable/Pair.tsx
src/utils/http.ts

Добавляет поддержку пар с дистанционной платформой вместо аудитории

feat&fix: add support for distance platform

---

src/parser/teachPlan.ts

fix: nested elective

---

src/parser/teachPlan.ts
src/tasks/signs.ts

каждый раз открывая код нотификаций удивляюсь все больше и больше

fix: notification npe

---

src/parser/timeTable.ts

в расписании не у всех недель присутсвует аттрибут title, оказывается
sentry report: cc8f6506

fix: timetable week title

---

src/screens/absences/AbsencesTable.tsx
src/screens/services/Menu.tsx

Иконка больше неиспользуется на экране пропусков, только в Menu.tsx; соответственно делать отдельную константу под нее нет смысла -> удалим её

refactor: remove global absencesIconName

---

src/screens/signs/SubjectCheckPoints.tsx

refactor: remove pass score from points

---

src/components/ClickableText.tsx
src/components/LoadingScreen.tsx
src/components/PageNavigator.tsx
src/screens/timeTable/TimeTable.tsx

Меня не раз просили добавить возможность скроллить навигатор по неделям.
Можно сказать, что этот пр удаляет старый навигатор по страницам и заменяет новым, с возможностью скроллить страницы, а не кликать по стрелкам.

feat: make page navigator scrollable

---

src/parser/timeTable.ts
src/screens/timeTable/Pair.tsx

Completes https://github.com/users/Damego/projects/1/views/3?pane=issue&itemId=39279161
Обновил regex, который ищет номера аудитории, корпуса и этажа и заставил экран использовать их

feat: remove building number dup in timeTable

---

src/data/demoClient.ts

Добавил демо-данные для личных записей и пропущенных занятий

chore: demo data update

---

src/screens/absences/AbsencesCard.tsx
src/screens/services/Menu.tsx

Изменил поведение страницы пропущенных занятий
* обрезал текст `Из них по уважительной причине` -> `По уважительной причине`
* строка `По уважительной причине` показывается лишь когда такие пропуски существуют
depends by #117

chore: absences fix

---

src/cache/smartCache.ts
src/data/base.ts
src/navigation/StackNavigator.tsx
src/navigation/TabNavigation.tsx
src/redux/reducers/settingsSlice.ts
src/screens/settings/Settings.tsx
src/screens/settings/ToggleSentrySetting.tsx
src/screens/settings/ToggleSignNotification.tsx
src/utils/consts.js
src/utils/sentry.ts
src/utils/shortcuts.ts

Интересная статистика: менее 5% пользователей генерируют около 93% всех ошибок в приложении.
Достаточно важное изменение, делающий Sentry включённым по умолчанию для всех пользователей, с возможностью выключения.

feat: set sentry enabled by default

---

src/models/teachers.ts
src/models/timeTable.ts
src/parser/teachers.ts
src/parser/timeTable.ts
src/screens/timeTable/Day.tsx
src/screens/timeTable/DayArray.tsx
src/screens/timeTable/Pair.tsx
src/screens/timeTable/TimeTable.tsx

Downloads the teachers info in the timeTable (only once, doesn't reload it on week change)
Closes https://github.com/users/Damego/projects/1/views/3?pane=issue&itemId=35601560

feat: show teacher's name in Lesson

---

src/screens/certificate/RequestCertificate.tsx

Окно об успешной отправке запроса на справку

chore: suсcessful certificate

---

src/models/timeTable.ts
src/parser/timeTable.ts
src/screens/timeTable/Pair.tsx
src/utils/sentry.ts

Also added reportReturn function into sentry.ts for convenience

fix: edge case for teacher not assigned or regex not passed

---

src/components/GradientContainer.tsx
src/components/HalloweenDecoration.tsx
src/screens/signs/TotalPoints.tsx

chore: halloween emoji on points

---

src/tasks/signs.ts
src/utils/notifications.ts

добавил базовые вещи в уведомление об оценках. идеи к сообщениям приветствуются

feat: signs notification messages

---

app.config.js
src/navigation/StackNavigator.tsx
src/screens/announce/AnnounceCard.tsx
src/screens/cathedraTimetable/CathedraTimetable.tsx
src/screens/certificate/RequestCertificate.tsx
src/screens/messages/Message.tsx
src/screens/messages/MessageInput.tsx
src/screens/sessionQuestionnaire/AdditionalComment.tsx
src/screens/settings/ChangeNewYearTheme.tsx
src/screens/settings/Settings.tsx
src/screens/timeTable/Pair.tsx
src/styles/themes.ts
src/utils/events.ts
src/utils/webView.ts

- Некорректные цвета в новогодних темах
- Ошибка в расписании преподавателей, если оно пустое
- Некорректная проверка условия для новогоднего события

merge: v1.2.4

---

package-lock.json
package.json
src/screens/teachers/Teacher.tsx
src/utils/consts.js
src/utils/http.ts

~Добавлена очередная новая библиотека, а то размер приложения не дотягивает до современных~
При клике на имя преподавателя открывается контекстное меню с двумя опциями:
1. Скопировать имя преподавателя
2. Найти преподавателя на сайте ПГНИУ
В объяснениях не нуждается

feat: add teacher search & context menu

---

src/parser/timeTable.ts

Исправлено определение ссылки на зум

fix: zoom link detection

---

src/hooks/useTimeTableQuery.ts
src/hooks/useTimetable.ts
src/redux/reducers/settingsSlice.ts
src/screens/etis/main/timetable/Timetable.tsx
src/screens/settings/uiSettings/ChangeAppUI.tsx
src/screens/settings/uiSettings/components/ToggleSkipSunday.tsx
src/screens/unauthorizedStudent/timetable/Timetable.tsx
src/screens/unauthorizedTeacher/timetable/Timetable.tsx

Добавляет новую настройку, при которой происходит автоматический переход на следующую неделю, если текущий день недели - воскресенье

feat: skip sunday
